### ISSUE TITLE
How to set up the environment?

### ISSUE THREAD

**Issue by syr-cn** [HelloWorldLTY/MuSe-GNN#2]
Congrats for your great work.

I met some problems when running the code for graph construction. Could you provide details about how to make a usable Python environment from scratch? I'm new to the R language and have difficulties installing the CSCORE package.

**Comment by HelloWorldLTY** [comment]
Hi, we actually do not use the R environment to run CS-CORE. CS-CORE has some updates and please refer their official repo for implementation: https://github.com/ChangSuBiostats/CS-CORE. 

My recommendation is to use a seperate environment for preprocessing, which contains R and python simtinuously. You can use rpy2 to link them. Please let me know if you have more questions.

**Comment by HelloWorldLTY** [comment]
Since there is no further request, I will close this issue. Thanks for your interests and good luck to your work:)
